### ISSUE TITLE
是没有上传到公共maven仓库吗？

### ISSUE THREAD

**Issue by lvdong** [dk900912/easyexcel-spring-boot#1]
是没有上传到公共maven仓库吗？

**Comment by dk900912** [comment]
已经上传了呀，最新版为 0.0.7 。https://search.maven.org/artifact/io.github.dk900912/easyexcel-spring-boot

此外，阿里云maven仓库也已经同步到了，也是能搜到的哈。https://developer.aliyun.com/mvn/search

**Comment by dk900912** [comment]
0.0.6 版本的确没发布，我的锅！没事，使用 0.0.7 吧 支持 xls xlsx csv 的导入导出，除了issue这种方式，还可以微信公众号（程序猿杜小头）来与我联系哈
